"use strict";
const content=document.getElementById('content'), tabs=document.getElementById('tabs');
const M={data:null,tab:'now',chapter:0,pending:false,paired:false,undo:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function localImage(url){try{const u=new URL(url,location.origin);return u.origin===location.origin&&u.pathname.startsWith('/assets/')?esc(u.pathname):''}catch{return ''}}
function message(text){const el=document.getElementById('message');el.textContent=text;el.style.display='block';clearTimeout(message.timer);message.timer=setTimeout(()=>el.style.display='none',5000)}
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok||data.ok===false)throw Object.assign(new Error(data.error||'Não foi possível concluir.'),{status:r.status});return data}
async function refresh(force=false){if(M.pending)return;try{const data=await api('/api/state');const changed=!M.data||M.data.version!==data.version||M.data.game.slug!==data.game.slug||JSON.stringify(M.data.answer)!==JSON.stringify(data.answer);if(M.data?.game.slug!==data.game.slug){M.chapter=0;M.undo=null}M.data=data;M.paired=true;tabs.hidden=false;document.getElementById('connection').textContent='Conectado ao PC';if(force||changed)render()}catch(e){document.getElementById('connection').textContent='Sem conexão';if(e.status===401){M.paired=false;tabs.hidden=true;content.innerHTML='<section class="card"><h1>Conexão encerrada</h1><p>Leia um novo QR Code no PC.</p></section>'}else if(force)message(e.message)}}
async function action(values){if(M.pending||!M.data)return;M.pending=true;content.querySelectorAll('button,input').forEach(e=>e.disabled=true);try{await api('/api/action',{slug:M.data.game.slug,version:M.data.version,...values});message('Salvo no PC');if(values.kind==='progress'&&values.action==='complete')M.undo={...values,value:!values.value};}catch(e){message(e.message)}finally{M.pending=false;await refresh(true)}}
function blockHTML(b){if(b.hidden)return `<article class="card"><h3>Spoiler oculto</h3><button data-reveal="${esc(b.id)}">Revelar este trecho</button></article>`;const done=(M.data.progress.completed||[]).includes(b.id);return `<article class="card ${['missable','warning'].includes(b.type)?'alert':''}"><span class="eyebrow">${esc(b.type==='missable'?'Aviso do guia':'Etapa')}</span><h2>${esc(b.title)}</h2><p class="text">${esc(b.text)}</p>${(b.items||[]).map(i=>`<p>• ${esc(i.text||i)}</p>`).join('')}<button class="check" data-complete="${esc(b.id)}" data-value="${!done}"><b>${done?'✓':'○'}</b>${done?'Concluído · desmarcar':'Marcar como concluído'}</button><button data-checkpoint="${esc(b.id)}">Continuar daqui</button></article>`}
function render(){const d=M.data;if(!d)return;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===M.tab));const chapters=d.chapters||[], chapter=chapters[Math.min(M.chapter,chapters.length-1)];let html=`<div class="eyebrow">${esc(d.game.platform)}</div><h1>${esc(d.game.title)}</h1>`;
if(M.tab==='now'){const objective=d.objective||{};html+=`<section class="card"><span class="eyebrow">Próximo objetivo</span><h2>${esc(objective.title||'Abra um capítulo do guia')}</h2><p>${esc(objective.text||objective.description||'O progresso marcado aqui também aparece no PC.')}</p><button class="primary" data-open-guide>Continuar no guia →</button></section>${(d.missables||[]).length?`<section class="card alert"><span class="eyebrow">Atenção · perdíveis</span>${d.missables.slice(0,3).map(a=>`<p>${esc(a.name)}${a.earned?' · Refazer em Hardcore':''}</p>`).join('')}</section>`:''}<section class="card"><h2>Seu controle de progresso</h2><p>${(d.progress.completed||[]).length} etapas concluídas. Requisitos e etapas são marcados manualmente.</p>${M.undo?'<button data-undo>Desfazer última conclusão</button>':''}</section>`}
if(M.tab==='guide'){html+=chapters.length?`<label for="chapter">Capítulo</label><select id="chapter">${chapters.map((c,i)=>`<option value="${i}" ${i===M.chapter?'selected':''}>${i+1}. ${esc(c.title)}</option>`).join('')}</select>${(chapter?.blocks||[]).map(blockHTML).join('')}<div class="actions"><button data-prev ${M.chapter===0?'disabled':''}>← Anterior</button><button data-next ${M.chapter>=chapters.length-1?'disabled':''}>Próximo →</button></div><form id="question-form" class="card"><h2>Perguntar sobre este trecho</h2><p>A pergunta e o trecho serão enviados ao provedor configurado no PC, sujeito a cobrança.</p><select name="block">${(chapter.blocks||[]).filter(b=>!b.hidden).map(b=>`<option value="${esc(b.id)}">${esc(b.title)}</option>`).join('')}</select><textarea name="question" maxlength="2000" placeholder="Qual é o próximo passo?" required></textarea><button class="primary" ${d.answer?.running?'disabled':''}>${d.answer?.running?'Consultando…':'Perguntar à IA'}</button>${d.answer?.answer?`<p class="text">${esc(d.answer.answer)}</p>`:''}${d.answer?.error?`<p>${esc(d.answer.error)}</p>`:''}</form>`:'<section class="card"><h2>O guia ainda não está pronto</h2><p>Importe e publique um guia no PC para continuar aqui.</p></section>'}
if(M.tab==='atlas'){html+=(d.systems||[]).map(s=>`<section class="card"><span class="eyebrow">Sistema visual</span><h2>${esc(s.title)}</h2><p>${esc(s.description)}</p>${s.nodes.map(n=>{const mediaId=d.system_state.node_media?.[`${s.id}:${n.id}`]||n.media_id;const image=localImage((d.media||[]).find(m=>m.id===mediaId)?.url||n.image?.url);return `<details class="node"><summary>${esc(n.label)} · ${esc(n.stage||'Detalhes')}</summary>${image?`<img src="${image}" alt="${esc(n.label)}">`:''}<button data-goal="${esc(n.id)}" data-system="${esc(s.id)}">Fixar como objetivo</button>${s.edges.filter(e=>e.to===n.id).map((e,i)=>`<h3>Caminho ${i+1} · ${esc(s.nodes.find(v=>v.id===e.from)?.label||'')}</h3>${e.requirements.map(r=>`<label class="requirement"><input type="checkbox" data-requirement="${esc(r.id)}" data-edge="${esc(e.id)}" data-system="${esc(s.id)}" ${(d.system_state.completed_requirements||[]).includes(r.id)?'checked':''}>${esc(r.text)}</label>`).join('')}`).join('')}</details>`}).join('')}</section>`).join('')||'<section class="card"><h2>Nenhum sistema publicado</h2><p>Crie e aprove um sistema no Atlas do PC. Prévias não são enviadas ao celular.</p></section>'}
if(M.tab==='achievements'){const rows=[...d.achievements].sort((a,b)=>Number(a.hardcore)-Number(b.hardcore));html+=rows.map(a=>`<article class="card"><div class="row"><span>${a.hardcore?'◆':a.earned?'◇':'○'}</span><div class="grow"><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p><small>${a.points||0} pontos · ${a.hardcore?'Hardcore':a.earned?'Softcore':'Pendente'}${a.achievement_type==='missable'?' · Perdível':''}</small></div></div></article>`).join('')||'<p>Nenhuma conquista sincronizada.</p>'}content.innerHTML=html;
content.querySelector('[data-open-guide]')?.addEventListener('click',()=>{M.tab='guide';const id=d.objective?.block_id;const i=chapters.findIndex(c=>c.blocks.some(b=>b.id===id));M.chapter=Math.max(0,i);render()});content.querySelector('#chapter')?.addEventListener('change',e=>{M.chapter=Number(e.target.value);render()});content.querySelector('[data-prev]')?.addEventListener('click',()=>{M.chapter--;render();window.scrollTo(0,0)});content.querySelector('[data-next]')?.addEventListener('click',()=>{M.chapter++;render();window.scrollTo(0,0)});
content.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>action({kind:'progress',action:'complete',block_id:b.dataset.complete,value:b.dataset.value==='true'}));content.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>action({kind:'progress',action:'reveal',block_id:b.dataset.reveal,value:true}));content.querySelectorAll('[data-checkpoint]').forEach(b=>b.onclick=()=>action({kind:'progress',action:'checkpoint',block_id:b.dataset.checkpoint,value:true}));content.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>action({kind:'goal',system_id:b.dataset.system,node_id:b.dataset.goal}));content.querySelectorAll('[data-requirement]').forEach(b=>b.onchange=()=>action({kind:'requirement',system_id:b.dataset.system,edge_id:b.dataset.edge,requirement_id:b.dataset.requirement,completed:b.checked}));content.querySelector('[data-undo]')?.addEventListener('click',async()=>{const undo=M.undo;M.undo=null;await action(undo);M.undo=null});content.querySelector('#question-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);action({kind:'ask',block_id:f.get('block'),question:f.get('question')})});}
tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{M.tab=b.dataset.tab;render();window.scrollTo(0,0)});
async function boot(){const code=new URLSearchParams(location.hash.slice(1)).get('pair');history.replaceState(null,'',location.pathname);if(code){try{await api('/pair',{code,name:/iPad|Tablet/i.test(navigator.userAgent)?'Tablet':'Celular'});content.innerHTML='<section class="card"><h1>Confirme no PC</h1><p>Abra Celular no DigiTracker e aprove este dispositivo.</p></section>';let waiting=true;while(waiting){await new Promise(r=>setTimeout(r,1500));const result=await api('/pair/status',{});waiting=result.pending}await refresh(true)}catch(e){message(e.message);document.getElementById('connection').textContent='Pareamento necessário'}}else await refresh(true)}
boot();setInterval(()=>{if(M.paired&&!document.hidden&&!['TEXTAREA','INPUT','SELECT'].includes(document.activeElement?.tagName))refresh()},3000);
