/* Global console navigation. Native overlays deliberately do not load this file. */
const XP={page:'home',hub:null,filter:'all',query:'',generation:0,searchGeneration:0,qr:'',settings:{},notifying:false};
function xpApplyTheme(){const platform=S.library.find(g=>g.slug===S.activeSlug)?.platform||'';const color=!XP.settings.platform_theme?'#6ad6ff':/playstation/i.test(platform)?'#53aaff':/xbox/i.test(platform)?'#99de80':/nintendo|gamecube|wii|switch/i.test(platform)?'#ff8294':'#6ad6ff';document.body.dataset.platformTheme=XP.settings.platform_theme?'enabled':'disabled';document.body.style.setProperty('--xp-cyan',color);}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&e.target===document){const modal=[...document.querySelectorAll('.modal-bg')].at(-1);if(modal){e.preventDefault();e.stopImmediatePropagation();const button=modal.querySelector('[data-modal-close],[id$="-close"],[id$="-cancel"]');if(button)button.click();else modal.remove()}}},true);
document.addEventListener('change',async e=>{if(e.target.id==='xp-notification-corner'){const r=await xpResult('set_notification_corner',e.target.value);if(r)toast(`Posição salva para ${r.emulator==='default'?'o padrão':r.emulator}.`)}});
async function xpCompareArt(view, url, candidate) {
  const modal=xpModal('Comparar e ajustar arte','<p role="status">Baixando e validando a imagem original… Sua arte atual ainda não foi alterada.</p>');
  const prepared=await appCall('prepare_art_preview',view.slug,url,{...candidate,query:candidate?.query||view.query});
  if(!modal.isConnected)return;
  if(!prepared.ok){modal.querySelector('p').textContent=prepared.error||'Não foi possível carregar. Escolha outra imagem.';return}
  const game=await backend.game(view.slug), role=view.role;
  const old=role==='background'?(game.art?.background||game.art?.title||game.art?.ingame):role==='icon'?game.art?.icon:xpCover(game);
  const section=modal.querySelector('section');
  section.insertAdjacentHTML('beforeend',`<div class="xp-art-compare"><figure><figcaption>Atual</figcaption>${old?`<img src="${esc(old)}" alt="Arte atual">`:'<p>Sem arte</p>'}</figure><figure><figcaption>Nova · ${prepared.width} × ${prepared.height}</figcaption><canvas id="xp-crop-canvas" width="600" height="430" aria-label="Seleção de recorte. Também pode usar os campos abaixo."></canvas></figure></div><p>Arraste sobre a nova imagem para selecionar um recorte. Nada será alterado antes de aplicar.</p><div class="xp-actions"><button data-crop-preset="full">Imagem inteira</button><button data-crop-preset="cover">Capa 2:3</button><button data-crop-preset="background">Fundo 16:9</button></div><details><summary>Ajustar recorte pelo teclado</summary><div class="xp-crop-fields">${[['x','Esquerda',0],['y','Topo',0],['width','Largura',100],['height','Altura',100]].map(([k,l,v])=>`<label>${l} (%)<input data-crop-number="${k}" type="number" min="${k==='x'||k==='y'?0:1}" max="100" value="${v}"></label>`).join('')}</div></details><div class="xp-actions"><button class="primary" id="xp-art-apply">Aplicar ${role==='background'?'fundo':role==='both'?'capa e fundo':role==='icon'?'ícone':'capa'}</button><button id="xp-art-cancel">Cancelar</button></div><p id="xp-art-error" role="status"></p>`);
  section.querySelector('p').remove();
  const canvas=section.querySelector('canvas'),context=canvas.getContext('2d'),image=new Image();let selection={x:0,y:0,width:1,height:1},bounds,anchor;
  function draw(){if(!image.naturalWidth)return;const scale=Math.min(canvas.width/image.naturalWidth,canvas.height/image.naturalHeight);bounds={x:(canvas.width-image.naturalWidth*scale)/2,y:(canvas.height-image.naturalHeight*scale)/2,w:image.naturalWidth*scale,h:image.naturalHeight*scale};context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(image,bounds.x,bounds.y,bounds.w,bounds.h);context.fillStyle='#001020aa';context.fillRect(0,0,canvas.width,canvas.height);const x=bounds.x+selection.x*bounds.w,y=bounds.y+selection.y*bounds.h,w=selection.width*bounds.w,h=selection.height*bounds.h;context.save();context.beginPath();context.rect(x,y,w,h);context.clip();context.drawImage(image,bounds.x,bounds.y,bounds.w,bounds.h);context.restore();context.strokeStyle='#70ddff';context.lineWidth=3;context.strokeRect(x,y,w,h);section.querySelectorAll('[data-crop-number]').forEach(input=>{if(document.activeElement!==input)input.value=Math.round(selection[input.dataset.cropNumber]*10000)/100})}
  image.onload=draw;image.onerror=()=>section.querySelector('#xp-art-error').textContent='Falha ao abrir a prévia local.';image.src=prepared.url;
  function position(e){const rect=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(1,((e.clientX-rect.left)/rect.width*canvas.width-bounds.x)/bounds.w)),y:Math.max(0,Math.min(1,((e.clientY-rect.top)/rect.height*canvas.height-bounds.y)/bounds.h))}}
  canvas.onpointerdown=e=>{if(!bounds)return;anchor=position(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!anchor)return;const end=position(e);selection={x:Math.min(anchor.x,end.x),y:Math.min(anchor.y,end.y),width:Math.abs(end.x-anchor.x),height:Math.abs(end.y-anchor.y)};draw()};canvas.onpointerup=canvas.onpointercancel=()=>{anchor=null};
  section.querySelectorAll('[data-crop-preset]').forEach(b=>b.onclick=()=>{selection={x:0,y:0,width:1,height:1};if(b.dataset.cropPreset!=='full'){const aspect=b.dataset.cropPreset==='cover'?2/3:16/9;const native=image.naturalWidth/image.naturalHeight;if(native>aspect){selection.width=aspect/native;selection.x=(1-selection.width)/2}else{selection.height=native/aspect;selection.y=(1-selection.height)/2}}draw()});
  section.querySelectorAll('[data-crop-number]').forEach(b=>b.oninput=()=>{selection[b.dataset.cropNumber]=Number(b.value)/100;draw()});
  section.querySelector('#xp-art-cancel').onclick=()=>modal.remove();section.querySelector('#xp-art-apply').onclick=async e=>{const button=e.target;button.disabled=true;button.textContent='Aplicando…';const result=await appCall('apply_art_preview',view.slug,prepared.token,role,selection);if(!result.ok){section.querySelector('#xp-art-error').textContent=result.error;button.disabled=false;button.textContent='Tentar novamente';return}modal.remove();closeCoverPicker();S.library=await backend.library();if(view.returnView==='settings')renderSettings();else await renderDashboard({force:true});toast('Arte aplicada. Você pode usar Desfazer no seletor.');};
}

document.addEventListener('click',async e=>{
  if(e.target.closest('[data-xp-export-library]')){const result=await xpResult('export_library_manifest');if(result)xpDownload('DigiTracker-biblioteca.json',JSON.stringify(result.document,null,2));}
  if(e.target.closest('[data-xp-import-library]')){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const file=input.files[0];if(!file)return;if(file.size>2*1024*1024)return toast('A biblioteca deve ter no máximo 2 MB.',true);let document;try{document=JSON.parse(await file.text())}catch{return toast('JSON inválido.',true)}const preview=await xpResult('import_library_manifest',document,false);if(!preview)return;const modal=xpModal('Importar biblioteca',`<p>${preview.count} jogos novos; ${preview.existing} já existentes serão preservados. As conquistas serão sincronizadas com sua conta atual da RetroAchievements. Guias e credenciais não são alterados.</p><button class="primary" id="xp-import-confirm">Confirmar importação</button>`);modal.querySelector('button#xp-import-confirm').onclick=async ev=>{ev.target.disabled=true;const result=await xpResult('import_library_manifest',document,true);if(result){modal.remove();toast(`${result.total} jogos na fila de importação.`)}else ev.target.disabled=false}};input.click();}
  if(e.target.closest('[data-xp-backup]')){const modal=xpModal('Backup completo',`<form class="xp-fields"><p>Inclui biblioteca, fontes, revisões, progresso, configurações e imagens locais. O ZIP será salvo em uma pasta “backups” ao lado do aplicativo.</p><label><span><input name="secrets" type="checkbox"> Incluir credenciais (exige senha)</span></label><label>Senha de proteção (opcional sem credenciais)<input name="password" type="password" autocomplete="new-password" minlength="12" placeholder="Pelo menos 12 caracteres"></label><p>Com senha, o arquivo usa AES-256. Guarde a senha: não há recuperação. Use um descompactador compatível, como 7-Zip.</p><button class="primary">Criar backup</button><p role="status" id="xp-backup-status"></p></form>`);modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const form=event.target,button=form.querySelector('button'),status=form.querySelector('#xp-backup-status');button.disabled=true;status.textContent='Criando uma cópia consistente dos dados…';const r=await appCall('create_local_backup',form.elements.secrets.checked,form.elements.password.value);form.elements.password.value='';if(r.ok){status.textContent=`Backup criado: ${r.path} (${r.files} arquivos).`;button.textContent='Concluído'}else{status.textContent=r.error;button.disabled=false}};}
});
const XP_NAV=[['home','⌂','Minha Jornada'],['library','▦','Biblioteca'],['hall','✦','Hall da Mastery'],['activity','◷','Atividade'],['phone','▱','Celular'],['settings','⚙','Configurações']];
document.addEventListener('click',e=>{const filter=e.target.closest('[data-xp-home-filter]');if(filter){XP.homeFilter=filter.dataset.xpHomeFilter;renderExperience('home')}});
function experienceNav(){return `<nav class="xp-nav" aria-label="Navegação principal">${XP_NAV.map(([key,icon,label])=>`<button data-xp-nav="${key}" class="${(S.view==='experience'&&XP.page===key)||(S.view==='hall'&&key==='hall')||(S.view==='dashboard'&&key==='library')?'active':''}"><i aria-hidden="true">${icon}</i>${label}</button>`).join('')}<button data-xp-search><i>⌕</i>Busca global<kbd>Ctrl K</kbd></button></nav>`}
function xpShell(body, embedded=false){
  const recent=[...(S.library||XP.hub?.games||[])].filter(g=>g.preferences?.opened_at>0).sort((a,b)=>b.preferences.opened_at-a.preferences.opened_at).slice(0,3);
  return `<div class="xp-shell xp-preview-a"><aside class="xp-side"><div class="xp-brand pywebview-drag-region"><i aria-hidden="true">◈</i>Digi<span>Tracker</span></div>${experienceNav()}<section class="xp-recent"><h2>Abertos recentemente</h2>${recent.map(g=>`<button data-xp-game="${esc(g.slug)}">${xpCover(g)?`<img src="${esc(xpCover(g))}" alt="">`:''}<span>${esc(g.title)}<small>${esc(xpStatus(g))}</small></span></button>`).join('')||'<p>Os jogos abertos aparecerão aqui.</p>'}</section><button class="xp-settings" data-xp-nav="settings">⚙ <span>Configurações</span></button></aside><div class="xp-workspace"><header class="xp-searchbar"><button data-xp-search><span>⌕</span> Buscar jogo, conquista ou guia <kbd>Ctrl K</kbd></button><button data-xp-nav="activity" aria-label="Abrir notificações">♧</button></header><div class="xp-page ${embedded?'xp-embedded':''}" data-scroll="experience">${body}</div></div></div>`;
}
function xpStatus(g){return isMastered(g)?'Mastery':({want:'Quero jogar',paused:'Pausado',playing:'Jogando agora'})[g.preferences?.status]||'Jogando agora'}
function xpJourneyCard(g){return `<article class="xp-journey-card"><button class="xp-landscape" data-xp-game="${esc(g.slug)}" aria-label="Abrir ${esc(g.title)}">${xpCover(g)?`<img src="${esc(xpCover(g))}" alt="">`:esc(g.title)}</button><button class="xp-star" data-xp-favorite="${esc(g.slug)}" aria-label="${g.preferences?.favorite?'Desafixar':'Fixar'} ${esc(g.title)}" aria-pressed="${!!g.preferences?.favorite}">${g.preferences?.favorite?'★':'☆'}</button><div><h3>${esc(g.title)}</h3><small class="xp-game-status">${esc(xpStatus(g))}</small><small>♜ ${g.mastery?.hardcore||0} / ${g.mastery?.total||0} · Hardcore · ${xpPct(g)}%</small><div class="xp-progress"><i style="width:${xpPct(g)}%"></i></div></div></article>`}
function xpPct(g){const m=g.mastery||{};return m.total?Math.round((m.hardcore||0)/m.total*100):0}
function xpTime(n){return `${Math.floor((n||0)/3600)}h ${Math.floor((n||0)%3600/60)}min`}
function xpCover(g){return g.art?.cover||g.art?.box||g.art?.icon||''}
function xpDate(n){return new Date(n*1000).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}
function xpEmpty(title,text){return `<section class="xp-empty"><span class="xp-eyebrow">Um passo de cada vez</span><h2>${esc(title)}</h2><p>${esc(text)}</p></section>`}
async function xpHub(){if(S.mode==='demo')return {ok:true,games:S.library.map(g=>({...g,preferences:g.preferences||{status:'playing',favorite:false,opened_at:0}})),goals:XP.hub?.goals||{points:1000,masteries:2},month_points:0,month_masteries:0,streak:0,settings:XP.settings};return appCall('get_journey_hub')}
async function xpResult(method,...args){const r=await appCall(method,...args);if(!r?.ok){toast(r?.error||'Não foi possível concluir. Tente novamente.',true);return null}return r}
async function xpOpenGame(slug,tab='journey',target=''){XP.generation++;S.experienceOpened=true;S.activeSlug=slug;S.tab=tab;S.guideReader=false;await enterDashboard();if(target){if(tab==='journey'){const game=S.dashboardGame;const chapters=game?.smart_guide?.current?.chapters||[];const i=chapters.findIndex(c=>(c.blocks||[]).some(b=>b.id===target));S.guideReader=true;S.guideChapter=Math.max(0,i);await renderDashboard({force:true})}requestAnimationFrame(()=>{const el=root.querySelector(`[data-guide-block="${CSS.escape(target)}"], [data-ach-id="${CSS.escape(target)}"]`);el?.scrollIntoView({block:'center'});if(el){el.tabIndex=-1;el.focus({preventScroll:true})}})}}
async function renderExperience(page='home'){if(S.compact)return;if(page==='settings'){await enterSettings();return}if(page==='hall'){await enterHall();return}XP.page=page;S.view='experience';stopPolling();const generation=++XP.generation;root.innerHTML=xpShell('<section class="xp-empty" role="status">Carregando sua jornada…</section>');document.getElementById('app').classList.remove('compact');document.getElementById('btn-library').hidden=true;const hub=await xpHub();if(generation!==XP.generation||S.view!=='experience')return;if(!hub?.ok){root.innerHTML=xpShell(xpEmpty('Não foi possível carregar',hub?.error||'Tente novamente.')+'<button data-xp-retry>Tentar novamente</button>');return}XP.hub=hub;XP.settings=hub.settings||{};document.body.classList.toggle('streamer-mode',!!XP.settings.streamer);let body='';if(page==='home')body=xpHome(hub);if(page==='library')body=xpLibrary(hub);if(page==='activity'){const r=S.mode==='demo'?{ok:true,events:[],...hub}:await appCall('get_activity',false);if(generation!==XP.generation)return;body=xpActivity(r)}if(page==='phone'){const r=S.mode==='demo'?{running:false,addresses:[],pending:[],devices:[]}:await appCall('get_companion_status');if(generation!==XP.generation)return;body=xpPhone(r)}if(page==='tools')body=xpTools();if(generation!==XP.generation||S.view!=='experience')return;root.innerHTML=xpShell(body);bindExperience();}
function xpGameCard(g){const m=g.mastery||{},p=g.preferences||{};return `<article class="xp-cover-card"><button class="xp-cover" data-xp-game="${esc(g.slug)}" aria-label="Abrir ${esc(g.title)}">${xpCover(g)?`<img loading="lazy" src="${esc(xpCover(g))}" alt="">`:`<span>${esc(initials(g.title))}</span>`}</button><button class="xp-star" data-xp-favorite="${esc(g.slug)}" aria-label="${p.favorite?'Desafixar':'Fixar'} ${esc(g.title)}" aria-pressed="${!!p.favorite}">${p.favorite?'★':'☆'}</button><h3>${esc(g.title)}</h3><small>${esc(g.platform||'')}</small><div class="xp-progress"><i style="width:${xpPct(g)}%"></i></div><small>${m.hardcore||0}/${m.total||0} · ${xpPct(g)}% HC${g.playtime?.label?` · ${esc(g.playtime.label)}`:''}</small><select data-xp-status="${esc(g.slug)}" aria-label="Estado de ${esc(g.title)}">${[['playing','Jogando agora'],['want','Quero jogar'],['paused','Pausado']].map(([v,l])=>`<option value="${v}" ${p.status===v?'selected':''}>${l}</option>`).join('')}</select></article>`}
function xpHome(h){
 const filter=XP.homeFilter||'all',active=h.games.filter(g=>!isMastered(g));
 const recent=[...active].sort((a,b)=>Number(!!b.preferences?.favorite)-Number(!!a.preferences?.favorite)||(b.preferences?.opened_at||0)-(a.preferences?.opened_at||0));
 const games=filter==='all'?recent:recent.filter(g=>filter==='softcore'?g.mastery?.total>0&&g.mastery?.earned>=g.mastery.total:(g.preferences?.status||'playing')===filter);
 const game=games.find(g=>g.slug===S.activeSlug)||games[0],session=h.session;
 const points=h.goals?.points||0,masteries=h.goals?.masteries||0;
 return `<div class="xp-a-heading"><div><h1>Minha Jornada</h1><p>Seu próximo passo, sem distrações.</p></div><button data-xp-nav="phone">▱ Conectar celular</button></div><nav class="xp-journey-tabs" aria-label="Filtrar jornada">${[['all','Todos'],['want','Quero jogar'],['playing','Jogando agora'],['paused','Pausados'],['softcore','Softcore']].map(([v,t])=>`<button data-xp-home-filter="${v}" aria-pressed="${filter===v}" class="${filter===v?'selected':''}">${t}</button>`).join('')}<button data-xp-nav="hall">Mastery</button></nav>
 ${game?`<section class="xp-hero">${game.art?.background||game.art?.hero||xpCover(game)?`<img src="${esc(game.art?.background||game.art?.hero||xpCover(game))}" alt="">`:''}<div class="xp-hero-copy"><span class="xp-eyebrow">▶ Continuar jogando</span><h2>${esc(game.title)}</h2><p class="xp-next">◎ Revisar o próximo objetivo no guia</p><p>♜ <strong>${game.mastery?.hardcore||0} / ${game.mastery?.total||0}</strong> &nbsp; Hardcore · ${xpPct(game)}%</p><button class="primary" data-xp-game="${esc(game.slug)}">Continuar no guia <span>›</span></button></div></section>`:xpEmpty('Sua próxima aventura','Nenhum jogo nesta seleção. Escolha outro filtro ou visite a biblioteca.')}
 <div class="xp-a-body"><section class="xp-playing"><div class="xp-section-heading"><h2>${filter==='all'?'Seus jogos':esc(({want:'Quero jogar',playing:'Jogando agora',paused:'Pausados',softcore:'Conclusão Softcore'})[filter])}</h2><button data-xp-nav="library">Ver todos ›</button></div><div class="xp-playing-grid">${games.slice(0,3).map(xpJourneyCard).join('')||'<p>Sem jogos neste filtro.</p>'}</div></section>
 <aside class="xp-month"><h2>Seu mês</h2><div class="xp-month-metric"><span>♜ Pontos Hardcore</span><strong>${h.month_points||0} <em>/ ${points||'—'}</em></strong><div class="xp-progress"><i style="width:${points?Math.min(100,(h.month_points||0)/points*100):0}%"></i></div></div><div class="xp-month-metric amber"><span>✦ Mastery</span><strong>${h.month_masteries||0} <em>/ ${masteries||'—'}</em></strong><div class="xp-progress"><i style="width:${masteries?Math.min(100,(h.month_masteries||0)/masteries*100):0}%"></i></div></div><div class="xp-actions"><button data-xp-goals>Editar metas</button><button data-xp-nav="activity">Metas e calendário ›</button></div></aside></div>
 <section class="xp-challenge"><span aria-hidden="true">◎</span><h2>Desafio da semana</h2><p>${esc(h.goals?.challenge||'Escolha sua próxima conquista.')}</p><button data-xp-goals>Escolher desafio ›</button></section>
 <section class="xp-session-line"><span>◷ ${session?xpTime(session.seconds):`${h.streak||0} dias de sequência`}</span><div class="xp-actions">${session&&session.status!=='ended'?`<button data-xp-session="${session.status==='running'?'pause':'resume'}">${session.status==='running'?'Pausar sessão':'Retomar sessão'}</button><button data-xp-session="end">Encerrar</button>`:`<button data-xp-session="start" data-slug="${esc(game?.slug||'')}" ${!game?'disabled':''}>Iniciar sessão</button>`}<button data-xp-nav="tools">Ferramentas e proteção</button></div></section>`;
}
function xpLibrary(h){let games=h.games.filter(g=>!isMastered(g));if(XP.filter==='favorites')games=games.filter(g=>g.preferences.favorite);else if(XP.filter==='softcore')games=games.filter(g=>g.mastery?.earned>=g.mastery?.total&&g.mastery?.total);else if(XP.filter!=='all')games=games.filter(g=>g.preferences.status===XP.filter);games=games.filter(g=>!XP.query||`${g.title} ${g.platform}`.toLocaleLowerCase('pt-BR').includes(XP.query.toLocaleLowerCase('pt-BR')));return `<div class="xp-topline"><div><span class="xp-eyebrow">Escolha sua próxima aventura</span><h1>Biblioteca</h1><p>${h.games.filter(g=>!isMastered(g)).length} jogos · Masteries ficam no Hall</p></div><div class="xp-actions"><button data-xp-add>＋ Adicionar jogo</button><button data-xp-nav="tools">Importar / exportar</button></div></div><div class="xp-toolbar">${[['all','Todos'],['playing','Jogando'],['want','Quero jogar'],['paused','Pausados'],['softcore','Softcore'],['favorites','★ Favoritos']].map(([v,t])=>`<button data-xp-filter="${v}" class="${v===XP.filter?'selected':''}">${t}</button>`).join('')}<input id="xp-library-search" value="${esc(XP.query)}" placeholder="Buscar jogo ou plataforma" aria-label="Buscar na biblioteca"></div><section class="xp-grid" id="xp-library-grid">${games.map(xpGameCard).join('')}</section>${games.length?'':xpEmpty('Nenhum jogo nesta seleção','Experimente outro filtro ou adicione um jogo.')}`}
function xpActivity(h){XP.notificationCorner=h.notification_corner||'bottom-left';const events=h.events||[],now=new Date(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const calendar=Array.from({length:days},(_,i)=>{const rows=events.filter(e=>{const d=new Date(e.at*1000);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()&&d.getDate()===i+1});return `<div class="xp-day ${rows.length?'has':''}" title="${rows.length} conquistas">${i+1}<small>${rows.length||'·'}</small></div>`}).join('');return `<div class="xp-topline"><div><span class="xp-eyebrow">Cada conquista conta</span><h1>Atividade</h1></div><button data-xp-notification-test>Testar popup</button></div><div class="xp-columns"><section class="xp-card"><h2>Conquistas recentes</h2>${events.map(e=>`<article class="xp-event">${e.badge_url?`<img src="${esc(e.badge_url)}" alt="">`:''}<div><span class="xp-mode">${esc(e.mode)}</span><b>${esc(e.name)}</b><small>${esc(e.game_title)} · ${e.points} pts · ${xpDate(e.at)}${e.rarity!=null?` · ${e.rarity}% dos jogadores`:''}</small></div><button data-xp-event="${esc(e.slug)}" data-target="${esc(e.achievement_id)}" aria-label="Abrir ${esc(e.name)}">→</button></article>`).join('')||'<p>As conquistas sincronizadas aparecerão aqui. A primeira importação não dispara popups antigos.</p>'}</section><aside><section class="xp-card"><span class="xp-eyebrow">${esc(now.toLocaleDateString('pt-BR',{month:'long',year:'numeric'}))}</span><h2>Calendário de conquistas</h2><div class="xp-calendar">${calendar}</div></section><section class="xp-card" style="margin-top:18px"><h2>Destaque da sessão</h2><p>${h.rarest?`${esc(h.rarest.name)} · ${h.rarest.rarity}% dos jogadores`:'Inicie uma sessão para acompanhar a conquista mais rara obtida nela.'}</p><small>Raridade informada pela RetroAchievements; não é uma medida absoluta de dificuldade.</small></section><section class="xp-card xp-fields" style="margin-top:18px"><h2>Seu ambiente</h2><label>Posição do popup para o emulador atual<select id="xp-notification-corner"><option value="bottom-left">Inferior esquerdo</option><option value="bottom-right">Inferior direito</option><option value="top-left">Superior esquerdo</option><option value="top-right">Superior direito</option></select></label>${[['silent','Modo silencioso (sem popup ou som)'],['sound','Som nas conquistas'],['streamer','Modo streamer (ocultar dados pessoais)'],['platform_theme','Cor contextual por plataforma']].map(([k,l])=>`<label><span><input type="checkbox" data-xp-setting="${k}" ${XP.settings[k]?'checked':''}> ${l}</span></label>`).join('')}</section></aside></div>`}
function xpPhone(r){if(!r?.ok&&S.mode!=='demo')return xpEmpty('Companion indisponível',r?.error||'Tente novamente.');return `<div class="xp-topline"><div><span class="xp-eyebrow">Sua segunda tela</span><h1>Celular e tablet</h1><p>Guia, mapas e progresso ao alcance da mão.</p></div><button data-xp-phone="refresh">Atualizar estado</button></div><div class="xp-columns"><section class="xp-card"><h2>${r.running?'Leia o QR Code':'Conecte pela sua rede local'}</h2><p>O PC precisa permanecer ligado e os dispositivos devem estar na mesma rede. Use somente Wi-Fi confiável: a conexão local usa HTTP, sem criptografia de transporte.</p>${r.running?`${XP.qr&&!XP.settings.streamer?`<img class="xp-qr" src="${XP.qr}" alt="QR Code temporário para pareamento">`:'<p>Gere um QR para conectar um novo dispositivo.</p>'}<p data-private>${esc(r.url||'')} · QR válido por 2 minutos</p><div class="xp-actions"><button class="primary" data-xp-phone="pair">Gerar novo QR</button><button data-xp-phone="stop">Desligar companion</button></div>`:`<label class="xp-fields">Endereço deste PC<select id="xp-phone-address">${(r.addresses||[]).map(a=>`<option value="${esc(a)}">${esc(a)}</option>`).join('')}</select></label><p>${r.addresses?.length?'Se o Windows solicitar, permita apenas redes privadas no firewall.':'Nenhuma interface de rede privada encontrada.'}</p><button class="primary" data-xp-phone="start" ${!r.addresses?.length?'disabled':''}>Iniciar companion</button>`}</section><section class="xp-card"><h2>Dispositivos e aprovação</h2><div id="xp-devices">${xpDevices(r)}</div><p>Apenas você aprova conexões. Chaves, credenciais, fontes completas e notas privadas não são compartilhadas.</p></section></div>`}
function xpDevices(r){return `${(r.pending||[]).map(d=>`<div class="xp-device"><div><b>${esc(d.name)}</b><p>Solicitando acesso</p></div><button data-xp-approve="${esc(d.id)}">Aprovar</button><button data-xp-reject="${esc(d.id)}">Recusar</button></div>`).join('')}${(r.devices||[]).map(d=>`<div class="xp-device"><div><b>${esc(d.name)}</b><p>Conectado · acesso por até 24 horas</p></div><button data-xp-revoke="${esc(d.id)}">Revogar</button></div>`).join('')||'<p>Nenhum dispositivo conectado.</p>'}`}
function xpTools(){return `<div class="xp-topline"><div><span class="xp-eyebrow">Seus dados sob controle</span><h1>Ferramentas e proteção</h1></div><button data-xp-nav="home">← Minha Jornada</button></div><div class="xp-columns"><section class="xp-card"><h2>Diagnóstico seguro</h2><p>Exporte um relatório técnico sem chaves, nomes de conta ou conteúdo dos guias.</p><button data-xp-diagnostics>Gerar diagnóstico</button><div id="xp-diagnostics"></div></section><section class="xp-card"><h2>Biblioteca e backup</h2><p>Exporte sua biblioteca ou crie uma cópia das configurações, guias e imagens. Credenciais ficam de fora por padrão.</p><div class="xp-actions"><button data-xp-export-library>Exportar biblioteca</button><button data-xp-import-library>Importar biblioteca</button><button class="primary" data-xp-backup>Backup completo</button></div></section></div>`}
function xpModal(title,html){const overlay=document.createElement('div');overlay.className='modal-bg';overlay.innerHTML=`<section class="xp-modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><h2>${esc(title)}</h2><button data-modal-close aria-label="Fechar">✕</button></header>${html}</section>`;overlay.querySelector('[data-modal-close]').onclick=()=>overlay.remove();document.body.appendChild(overlay);return overlay}
function xpDownload(name,data,mime='application/json'){const url=URL.createObjectURL(new Blob([data],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000)}
function bindExperience(){xpApplyTheme();const corner=root.querySelector('#xp-notification-corner');if(corner)corner.value=XP.notificationCorner||'bottom-left';root.querySelectorAll('[data-xp-favorite]').forEach(b=>b.onclick=async()=>{const g=XP.hub.games.find(g=>g.slug===b.dataset.xpFavorite);if(await xpResult('set_game_preferences',g.slug,{favorite:!g.preferences.favorite}))renderExperience(XP.page)});root.querySelectorAll('[data-xp-status]').forEach(b=>b.onchange=async()=>{if(await xpResult('set_game_preferences',b.dataset.xpStatus,{status:b.value}))renderExperience(XP.page)});root.querySelectorAll('[data-xp-filter]').forEach(b=>b.onclick=()=>{XP.filter=b.dataset.xpFilter;root.querySelector('.xp-page').innerHTML=xpLibrary(XP.hub);bindExperience()});root.querySelector('#xp-library-search')?.addEventListener('input',e=>{XP.query=e.target.value;clearTimeout(XP.searchTimer);XP.searchTimer=setTimeout(()=>{const start=e.target.selectionStart;root.querySelector('.xp-page').innerHTML=xpLibrary(XP.hub);bindExperience();const input=root.querySelector('#xp-library-search');input.focus();try{input.setSelectionRange(start,start)}catch{}},200)});root.querySelectorAll('[data-xp-session]').forEach(b=>b.onclick=async()=>{if(await xpResult('control_session',b.dataset.xpSession,b.dataset.slug||''))renderExperience('home')});root.querySelectorAll('[data-xp-setting]').forEach(b=>b.onchange=async()=>{const r=await xpResult('set_productivity_settings',{[b.dataset.xpSetting]:b.checked});if(r){XP.settings=r.settings;document.body.classList.toggle('streamer-mode',!!XP.settings.streamer);document.body.dataset.platformTheme=XP.settings.platform_theme?'enabled':'disabled';toast('Preferência salva.')}else b.checked=!b.checked});root.querySelectorAll('[data-xp-goals]').forEach(b=>b.addEventListener('click',xpGoals));root.querySelector('[data-xp-diagnostics]')?.addEventListener('click',async()=>{const r=await xpResult('get_diagnostics_report');if(!r)return;const data=JSON.stringify(r.report,null,2);const el=root.querySelector('#xp-diagnostics');el.innerHTML=`<pre>${esc(data)}</pre><button id="xp-save-report">Exportar JSON</button>`;el.querySelector('button').onclick=()=>xpDownload('DigiTracker-diagnostico.json',data)});root.querySelector('[data-xp-notification-test]')?.addEventListener('click',async()=>{const r=await appCall('test_achievement_notification');if(r.native)return;return xpShowNotification({name:'Conquista de demonstração',game_title:'Teste de notificação',mode:'hardcore',points:10,rarity:5,slug:S.activeSlug},true)});}
function xpGoals(){const g=XP.hub.goals||{};const m=xpModal('Metas da sua jornada',`<form class="xp-fields"><label>Pontos Hardcore neste mês<input name="points" type="number" min="0" max="1000000" value="${g.points||0}"></label><label>Jogos masterizados no mês<input name="masteries" type="number" min="0" max="1000" value="${g.masteries||0}"></label><label>Desafio da semana<textarea name="challenge" maxlength="500">${esc(g.challenge||'')}</textarea></label><button class="primary">Salvar metas</button></form>`);m.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(await xpResult('set_journey_goals',f)){m.remove();renderExperience('home')}}}
async function xpSearch(){if(S.compact)return;const m=xpModal('Busca global',`<input class="xp-search-input" placeholder="Jogo, conquista, guia ou anotação…" aria-label="Busca global"><div id="xp-results" role="status"><p>Digite para procurar na sua biblioteca local.</p></div>`);const input=m.querySelector('input'),results=m.querySelector('#xp-results');input.oninput=()=>{clearTimeout(XP.globalTimer);const token=++XP.searchGeneration;XP.globalTimer=setTimeout(async()=>{results.innerHTML='<p>Buscando…</p>';const r=await appCall('search_everywhere',input.value);if(!m.isConnected||token!==XP.searchGeneration)return;results.innerHTML=r.ok?(r.results.map(v=>`<button class="xp-result" data-slug="${esc(v.slug)}" data-kind="${esc(v.kind)}" data-target="${esc(v.target)}"><b>${esc(v.title)}</b><small>${esc(({game:'Jogo',achievement:'Conquista',guide:'Guia',note:'Anotação'})[v.kind])} · ${esc(v.snippet)}</small></button>`).join('')||'<p>Nenhum resultado encontrado.</p>'):`<p>${esc(r.error)}</p>`;results.querySelectorAll('button').forEach(b=>b.onclick=()=>{m.remove();xpOpenGame(b.dataset.slug,b.dataset.kind==='achievement'?'achievements':'journey',b.dataset.target)})},180)};input.focus()}
function xpShowNotification(e,test=false){if(XP.settings.silent&&!test)return Promise.resolve();return new Promise(resolve=>{const card=document.createElement('button');card.className='xp-toast';card.setAttribute('aria-label',`Conquista: ${e.name}. Abrir no jogo.`);card.innerHTML=`${e.badge_url?`<img src="${esc(e.badge_url)}" alt="">`:''}<div><small>${e.mode==='hardcore'?'◆ HARDCORE':'◇ SOFTCORE'} · CONQUISTA OBTIDA</small><b>${esc(e.name)}</b><span>${e.points||0} pontos${e.rarity!=null?` · ${e.rarity}% dos jogadores`:''}</span></div>`;document.body.appendChild(card);card.onclick=()=>{card.remove();if(!test)xpOpenGame(e.slug,'achievements',String(e.achievement_id));resolve()};if(XP.settings.sound){try{const audio=new AudioContext(),osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(660,audio.currentTime);osc.frequency.setValueAtTime(880,audio.currentTime+.15);gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.45);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.5);osc.onended=()=>audio.close()}catch{}}setTimeout(()=>{card.remove();resolve()},6000)})}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-xp-nav]');if(nav){await renderExperience(nav.dataset.xpNav);return}if(e.target.closest('[data-xp-search]'))return xpSearch();const game=e.target.closest('[data-xp-game]');if(game)return xpOpenGame(game.dataset.xpGame);const event=e.target.closest('[data-xp-event]');if(event)return xpOpenGame(event.dataset.xpEvent,'achievements',event.dataset.target);if(e.target.closest('[data-xp-retry]'))return renderExperience(XP.page);if(e.target.closest('[data-xp-add]')){await xpOpenGame(S.activeSlug);document.getElementById('btn-add')?.click();return}const phone=e.target.closest('[data-xp-phone]');if(phone){phone.disabled=true;const a=phone.dataset.xpPhone;let r;if(a==='refresh')r=await xpResult('get_companion_status');if(a==='start')r=await xpResult('start_companion',document.getElementById('xp-phone-address').value);if(a==='pair')r=await xpResult('new_companion_pairing');if(a==='stop'){r=await xpResult('stop_companion');XP.qr=''}if(r?.qr)XP.qr=r.qr;if(r)await renderExperience('phone');else phone.disabled=false;return}for(const [attr,method,arg] of [['xpApprove','approve_companion',true],['xpReject','approve_companion',false],['xpRevoke','revoke_companion',null]]){const b=e.target.closest(`[data-${attr.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}]`);if(b){if(await xpResult(method,b.dataset[attr],...(arg===null?[]:[arg])))renderExperience('phone');return}}});
document.addEventListener('keydown',e=>{if(!S.compact&&e.ctrlKey&&!e.altKey&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();if(S.view!=='settings')xpSearch()}},true);
setInterval(async()=>{if(S.mode==='demo'||S.view==='loading'||S.view==='setup')return;if(S.view==='experience'&&XP.page==='phone'){const r=await appCall('get_companion_status');const node=document.getElementById('xp-devices');if(node&&r.ok&&!node.contains(document.activeElement))node.innerHTML=xpDevices(r)}if(XP.notifying||S.compact||document.hidden)return;XP.notifying=true;try{const r=await appCall('get_activity',true);XP.settings=r.settings||XP.settings;if(r.native_notifications)return;for(const event of (r.events||[]).slice().reverse().slice(0,5)){await xpShowNotification(event);await appCall('acknowledge_notification',event.id)}}finally{XP.notifying=false}},5000);
